### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by ajmeese7** [meeseOS/meeseOS#5]
I would love to boot into a custom terminal on startup, with one of the commands being an option to launch a GUI for the desktop.

## Task List
- [x] Pick and implement a custom terminal
- [x] Automatically log in to the terminal with SSHPass
- [x] Install [oh-my-posh](https://ohmyposh.dev/docs/linux) on setup, so the terminal is styled prettier
    - [x] Configure oh-my-posh for the chrooted user
- [x] Unbreak the terminal
    - [x] Upgrade the Terminal app to my fork of dev-meta and get the dependencies to all the latest
- [x] Install a Nerd Font automatically for use with `oh-my-posh`
    - [ ] Make the Nerd Font the default terminal font without the GUI
- [x] Have a custom greeting when launching the terminal application (MOTD)
- [ ] Configure the terminal to use the Nerd Font as the default terminal font
- [ ] Boot into a custom terminal on startup
    - Could use [Sid's Term](https://github.com/sidpagariya/term) for this
- [ ] Make the OS mode (GUI/CLI) be cached and stored, so the user can boot back into whatever mode they had previously selected with nothing required on their end
- [ ] Add cool custom commands
- [x] Secure xterm SSH
    - [x] [Hide banner](https://unix.stackexchange.com/a/96982/370076)

## Additional Resources
- [Node.js CLI Guide](https://x-team.com/blog/a-guide-to-creating-a-nodejs-command/)
- [JS CLI Guide](https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/)
- [Custom Commands S/O](https://stackoverflow.com/questions/60022994/adding-custom-commands-to-terminal-along-side-application)
    - Can implement with [salvah](https://github.com/shalvah/shalvah.github.io/tree/v2), with a detailed guide [here](https://blog.shalvah.me/posts/i-was-bored-so-i-made-my-website-into-a-node-package-heres-how)

**Comment by ajmeese7** [comment]
Converting this into a tracking epic. It is roughly 80% done; the remaining unchecked work has been split into focused, individually actionable issues:

- https://github.com/meese-os/meeseOS/issues/206
- https://github.com/meese-os/meeseOS/issues/207

The remaining "add cool custom commands" item is too open-ended to split usefully and will stay here in the epic until it is concrete. Leaving this issue open as the tracker.
